// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe89jfoHbjRLF-28eJfuPVs4VEmsye0bY',
    appId: '1:403335323247:web:30c65d83fee206852a779a',
    messagingSenderId: '403335323247',
    projectId: 'koolkwiz',
    authDomain: 'koolkwiz.firebaseapp.com',
    storageBucket: 'koolkwiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXJYLfdBSqWu9KoQt0v8-PND7tPa_XpM',
    appId: '1:403335323247:android:9f70b244dae22bcf2a779a',
    messagingSenderId: '403335323247',
    projectId: 'koolkwiz',
    storageBucket: 'koolkwiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM9SVY8O3LduDvSVfPq8kVUF8KD4cZVQ4',
    appId: '1:403335323247:ios:c1f6101be9ef3b962a779a',
    messagingSenderId: '403335323247',
    projectId: 'koolkwiz',
    storageBucket: 'koolkwiz.appspot.com',
    iosClientId: '403335323247-t4qthkaqh8l0484f6u3bdts04m9p303k.apps.googleusercontent.com',
    iosBundleId: 'com.example.koolkwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM9SVY8O3LduDvSVfPq8kVUF8KD4cZVQ4',
    appId: '1:403335323247:ios:d6741feda108c6ab2a779a',
    messagingSenderId: '403335323247',
    projectId: 'koolkwiz',
    storageBucket: 'koolkwiz.appspot.com',
    iosClientId: '403335323247-q71nm55bjngoam4d2taegcuvsufbpniv.apps.googleusercontent.com',
    iosBundleId: 'com.example.koolkwiz.RunnerTests',
  );
}
